export const locators = {
  loginButton: "div.auth-bar__item.auth-bar__item--text",
  username: 'input[placeholder="Ник или e-mail"]',
  password: 'input[placeholder="Пароль"]',
  loginButtonField:
    "div.auth-form__control.auth-form__control_condensed-additional",
  loginButtonOnPage: 'button[type="submit"]',
  validationError: "div.auth-form__description.auth-form__description_error",
  inputField: "input.fast-search__input",
  searchInput: 'input[placeholder="Поиск"]',
  catalogField: "li.b-main-navigation__item",
  catalogButton: '[href="https://catalog.onliner.by"]',
  primary: "a.catalog-navigation__bubble.catalog-navigation__bubble_primary",
  superPrice: "h1.schema-header__title.js-super-price-title",
  category: '[class="result__item result__item_category"]',
  iframeSearchResult: "ul.search__results",
  iframe: "iframe.modal-iframe",
  loginCaptcha: "div.auth-form__title.auth-form__title_base",
  cartButton: "a.auth-bar__item.auth-bar__item--cart",
  emptyCart: "div.cart-message__title.cart-message__title_big",
  currencyLink:
    "[class*=js-currency-widget] [class=b-top-navigation-informers__link]",
  currencyConverter: 'input[name="amount-in"]',
  curResult: "b.js-cur-result",
  weatherLink: "span._u.js-weather",
  weatherCity: "a.js-weather-city",
  polotskCity: 'a[data-wmoid="26653"]',
  techSupport: 'a[href="https://support.onliner.by"]',
  techSupportSubmit: 'input[name="supportform[submit]"]',
  techSupportError: 'div[id="id_error"]',
  advertisement: 'a[href="https://b2breg.onliner.by/advertising"]',
  contactPhone: 'input[placeholder="Контактный телефон"]',
  contactEmail: 'input[placeholder="Контактный email"]',
  sendButton: 'button[type="submit"]',
  advertisementPhoneError:
    '(//div[@class="input-style__wrapper b2breg-form__input-wrapper"])[1]',
  advertisementEmailError:
    '(//div[@class="input-style__wrapper b2breg-form__input-wrapper"])[2]',
  successMessage: "div.title-style.title-style_primary-alter.title-style_huge",
  findCars:
    'a[data-utm="utm_source=onliner&utm_medium=main_page&utm_content=listing"]',
  carFleaMarket: "h1.vehicle-form__title.vehicle-form__title_big-alter",
};
